### ISSUE TITLE
Docker compose minor formatting issue

### ISSUE THREAD

**Issue by profucius** [foofus-sph1nx/Proxmox-LXC-Docker-Windows#1]
First thanks for putting this little guide together. You saved me some time getting the process started. I just wanted to mention an issue with the formatting of your docker compose, the tabulation levels of some lines were a bit off. I fixed it on my end and pasted it below. Exact same content just the level3/4 lines are tabbed properly. That's all, thanks!

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    networks:
      macvlan1:
        ipv4_address: x.x.x.x
    privileged: true
    environment:
      - VERSION: "10"
      - DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
    volumes:
      - /home/storage:/data
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    sysctls:
      - net.ipv4.ip_forward=1
networks:
  macvlan1:
    external: true
```
